FROM quay.io/keycloak/keycloak:26.1.0

ADD  --chown=keycloak:keycloak https://github.com/aznamier/keycloak-event-listener-rabbitmq/releases/download/3.0.5/keycloak-to-rabbit-3.0.5.jar \
    /opt/keycloak/providers/keycloak-to-rabbit-3.0.5.jar
