syntax = "proto3";
option csharp_namespace = "Protos";
import "google/protobuf/empty.proto";
service ProfileService {
  rpc GetUserProfile (GetUserProfileRequest) returns (GetUserProfileResponse);
  rpc GetAuthCheck (google.protobuf.Empty) returns (google.protobuf.Empty);
  rpc GetUserSnapshot (GetUserSnapshotRequest) returns (GetUserSnapshotResponse);
}

message GetUserProfileRequest {
  string user_id = 1;
}
message GetUserProfileResponse {
  string user_id = 1;
  string username = 2;
  string email = 3;
  string avatar_url = 4;
}

message GetUserSnapshotRequest {
  string user_id = 1;
}
message GetUserSnapshotResponse {
  string user_id = 1;
  string username = 2;
  string avatar_url = 3;
}